package m1.pkg1;

import java.sql.*;
import java.util.Scanner;

public class ExhibitService {
    private Scanner sc = new Scanner(System.in);

        // ==========================================================
            // FEATURE: SEARCH EXHIBIT INFORMATION
                // ==========================================================
                    public void searchExhibit() {
                        sc = new Scanner(System.in); 
                            System.out.println("\n--- [ SYSTEM: SEARCHING DATABASE... ] ---");
                                System.out.print("Enter Exact Exhibit Title: ");
                                    String keyword = sc.nextLine().trim(); 

                                        String query = "SELECT * FROM exhibits WHERE title = ?";
                                            
                                                try (Connection conn = Database.getConnection();
                                                         PreparedStatement pstmt = conn.prepareStatement(query)) {
                                                                 
                                                                         pstmt.setString(1, keyword); 
                                                                                 ResultSet rs = pstmt.executeQuery();

                                                                                         if (rs.next()) {
                                                                                                     System.out.println("\n==================================================");
                                                                                                                 System.out.println("         ✨ EXHIBIT DETAILED PROFILE ✨          ");
                                                                                                                             System.out.println("==================================================");
                                                                                                                                         System.out.println("NAME         : " + rs.getString("title").toUpperCase());
                                                                                                                                                     System.out.println("ERA/ORIGIN   : " + rs.getString("era_location"));
                                                                                                                                                                 System.out.println("CATALOG ID   : MUSEUM-ID-" + rs.getInt("exhibit_id"));
                                                                                                                                                                             System.out.println("STATUS       : [ ON DISPLAY - GALLERY 1 ]"); // Added info
                                                                                                                                                                                         System.out.println("--------------------------------------------------");
                                                                                                                                                                                                     System.out.println("📜 HISTORICAL DESCRIPTION:");
                                                                                                                                                                                                                 System.out.println(rs.getString("description"));
                                                                                                                                                                                                                             System.out.println("--------------------------------------------------");
                                                                                                                                                                                                                                         System.out.println("🖼️ MULTIMEDIA REFERENCE: " + rs.getString("multimedia"));
                                                                                                                                                                                                                                                     System.out.println("💡 RELATED INFO: Original artwork preserved in the National Museum.");
                                                                                                                                                                                                                                                                 System.out.println("==================================================");
                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                     // Requirement: Show error message if not found
                                                                                                                                                                                                                                                                                                 System.out.println("\n>>> [!] ERROR: Exhibit information unavailable.");
                                                                                                                                                                                                                                                                                                             System.out.println("Check spelling or contact the Museum Curator.");
                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                         } catch (SQLException e) {
                                                                                                                                                                                                                                                                                                                                 System.out.println("Database Error: " + e.getMessage());
                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                         // ==========================================================
                                                                                                                                                                                                                                                                                                                                             // FEATURE: EXPLORE FULL GALLERY (VIRTUAL TOUR)
                                                                                                                                                                                                                                                                                                                                                 // ==========================================================
                                                                                                                                                                                                                                                                                                                                                     public void exploreGallery() {
                                                                                                                                                                                                                                                                                                                                                             System.out.println("\n--- NATIONAL MUSEUM VIRTUAL GALLERY ---");
                                                                                                                                                                                                                                                                                                                                                                     // Naka-order para sunod-sunod ang tour
                                                                                                                                                                                                                                                                                                                                                                             String query = "SELECT * FROM exhibits ORDER BY exhibit_id ASC";

                                                                                                                                                                                                                                                                                                                                                                                     try (Connection conn = Database.getConnection();
                                                                                                                                                                                                                                                                                                                                                                                                  Statement stmt = conn.createStatement();
                                                                                                                                                                                                                                                                                                                                                                                                               ResultSet rs = stmt.executeQuery(query)) {

                                                                                                                                                                                                                                                                                                                                                                                                                           boolean touring = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                       while (rs.next() && touring) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("\n==================================================");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("EXHIBIT ID:  " + rs.getInt("exhibit_id"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("TITLE:       " + rs.getString("title"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("ERA/LOC:     " + rs.getString("era_location"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("--------------------------------------------------");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("DESCRIPTION: \n" + rs.getString("description"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("\nMULTIMEDIA:  [" + rs.getString("multimedia") + "]");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("==================================================");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.println("\n[ANY KEY] for Next Exhibit | [X] to Exit Gallery");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       System.out.print("Action > ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       String action = sc.next();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (action.equalsIgnoreCase("X")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           touring = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               System.out.println("Exiting Gallery...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (touring) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   System.out.println("\n>>> End of the gallery reached. Thank you for viewing!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   } catch (SQLException e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               System.out.println("Gallery Error: Exhibit information unavailable.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }